# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Make the builder script executable
RUN chmod +x config/builder.sh

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV PATH="/app:$PATH"

# Run bashbunny when the container launches
CMD ["bash builder.sh"]