# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
#RUN pip install -r requirements.txt

# Make the builder script executable
RUN chmod +x config/builder.sh

# Run the builder
RUN pwd
RUN ls -la

# Run the builder
RUN bash /config/builder.sh

# Define environment variable
ENV PATH="/app:$PATH"